name: Deploy to MySQL

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    flyway-migration:
        runs-on: self-hosted # runner locale

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 # Per recuperare il codice dal repository

            - name: Set up Java
              uses: actions/setup-java@v3 # Flyway richiede Java
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Install Flyway
              run: |
                  # download e install Flyway
                  curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.21.1/flyway-commandline-9.21.1-linux-x64.tar.gz | tar xz
                  sudo ln -s $PWD/flyway-*/flyway /usr/local/bin/flyway

            - name: Run migrations
              env:
                  FLYWAY_URL: ${{ secrets.FLYWAY_URL }} # URL del database
                  FLYWAY_USER: ${{ secrets.FLYWAY_USER }} # User del database
                  FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }} # Password del database
              run: flyway migrate -configFiles=flyway.conf # Esegui le migrazioni
